### ISSUE TITLE
Transparent fees

### ISSUE THREAD

**Issue by gotjoshua** [terra-project/shuttle#12]
I sent 5 UDT ([Terra Tx](https://finder.terra.money/columbus-4/tx/2224752695BDDC778E862A2FDEA5835A9266965FC70F6C027123793E99AF7F5E))and got 4 wrapped UDT ([ETH Tx](https://etherscan.io/tx/0x25923270b55f1e187aec2a5cba17128d78044a3f962392c0f1e99f2d74245415))

How can one calculate the amount of wUDT that will arrive?

**Comment by octalmage** [comment]
It's in the docs: http://bsc.mirror.finance exists for going from BSC to Terra.

**Comment by octalmage** [comment]
See: https://github.com/terra-project/shuttle#relaying-fee
