### ISSUE TITLE
How can I transfer from BSC to Terra

### ISSUE THREAD

**Issue by dominixz** [terra-project/shuttle#13]
I tried to understand but I'm not so my question is it possible to transfer from BSC to Terra right now?

If so, How can I do that in step by step?

Thank in advance

**Comment by g8d3** [comment]
I tried this:

```javascript
b=require('bech32')
bb=b.decode(process.argv[2])
// bb=b.decode('terra1t849fxw7e8ney35mxemh4h3ayea4zf77dslwna')
// hex: 59ea5499dec9e792469b36777ade3d267b5127de9
z24 = '000000000000000000000000'

unbech32 = bb.words
    .map(e=> e.toString(2).padStart(5,0)).join('')
    .match(/\d{4}/g).map(e=>parseInt(e,2).toString(16)).join('')
    
unbech32 += z24

console.log(unbech32)
```

Unfortunately I am getting `59ea5499dec9e792469b36777ade3d267b5127de000000000000000000000000`, while it should be `59ea5499dec9e792469b36777ade3d267b5127de900000000000000000000000`

I am not sure about the `9`.

**Comment by octalmage** [comment]
http://bsc.mirror.finance/ includes an interface for this! And their code is on GitHub.
