### ISSUE TITLE
Official GUI?

### ISSUE THREAD

**Issue by AlexLeung** [terra-project/shuttle#17]
Is there an official GUI for submitting shuttle transactions or does it all need to be done with our own CLI for now?

**Comment by octalmage** [comment]
There's multiple GUIs, Terra Station has a UI for sending transactions from Tera to ETH and BSC. 


http://bsc.mirror.finance exists for going from BSC to Terra. 
http://eth.mirror.finance exists for going from ETH to Terra.

**Comment by YunSuk-Yeo** [comment]
I think the issue is resolved

**Comment by AlexLeung** [comment]
As far as I can see, http://eth.mirror.finance only offers a GUI to to stage LP tokens. There's no GUI for bridging from ETH to Terra or vice versa

**Comment by AlexLeung** [comment]
There's no bridge button here

![image](https://user-images.githubusercontent.com/5025138/113489223-d45fcf80-9477-11eb-9b02-6d47abe14eae.png)

**Comment by AlexLeung** [comment]
Found it https://bridge.terra.money/
